---

name: ubuntu

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    container: deividrodriguez/byebug:${{ matrix.version }}-${{ matrix.line_editor }}-${{ matrix.compiler }}

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false

      matrix:
        version: [3.1.6, 3.2.5, 3.3.3]
        line_editor: [libedit, readline]
        compiler: [clang, gcc]

    steps:
      - uses: actions/checkout@v1

      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake

      - name: Save coverage
        run: mv coverage/.resultset.json coverage/${{ matrix.version }}-${{ matrix.line_editor }}-${{ matrix.compiler }}.json
        if: startsWith(matrix.version, '3.3')

      - uses: actions/upload-artifact@v1
        with:
          name: coverage-${{ matrix.version }}-${{ matrix.line_editor }}-${{ matrix.compiler }}
          path: coverage/${{ matrix.version }}-${{ matrix.line_editor }}-${{ matrix.compiler }}.json
        if: startsWith(matrix.version, '3.3')

    timeout-minutes: 15

  coverage:
    container: deividrodriguez/byebug:3.3.3-readline-gcc

    runs-on: ubuntu-24.04

    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v1
        with:
          name: coverage-3.3.3-libedit-clang
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-3.3.3-libedit-gcc
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-3.3.3-readline-clang
          path: coverage

      - uses: actions/download-artifact@v1
        with:
          name: coverage-3.3.3-readline-gcc
          path: coverage

      - name: Aggregate coverage results
        run: |
          bin/setup.sh
          bin/rake coverage:collate
